apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1002"
  name: external-secrets-stores
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          clusterId: in-cluster-local
      values:
        path: external-secrets-stores/0.5.9/overlays/clusters/in-cluster-local
  template:
    metadata:
      name: 'external-secrets-stores-{{name}}'
      labels:
        appset: external-secrets-stores
        clusterId: '{{metadata.labels.clusterId}}'
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1002"
        version: '{{values.path}}'
    spec:
      project: external-secrets
      source:
        repoURL: 'https://github.com/ron1/ron1-external-secrets-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
