external-secrets:
  installCRDs: true
  replicaCount: 1
  extraVolumes: []
  extraVolumeMounts: []
  serviceMonitor:
    enabled: false
  certController:
    replicaCount: 1
  webhook:
    replicaCount: 1
